apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "wavefront-hpa-adapter.fullname" . }}
  labels:
{{ include "wavefront-hpa-adapter.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "wavefront-hpa-adapter.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "wavefront-hpa-adapter.fullname" . }}
  namespace: {{ .Release.Namespace }}
